### ISSUE TITLE
Endpoint "/tenant_propose" returns 404

### ISSUE THREAD

**Issue by ondrej-kristejn** [TeskaLabs/seacat-auth#85]
The "create new tenant" section on the administration web-page has a button "Propose a name", which when clicked fails with error:
```
Something went wrong, can't propose tenant name
```
Using curl on `/seacat/api/seacat_auth/public/tenant_propose` It looks like non-existent endpoint:
```
{"result": "NOT-FOUND", "message": "404: Not Found", "uuid": "fb4e82a0-6e0e-4069-99a1-001dae642194"}
```

_seacat version: v22.30_
_web-ui administration version: (Build date Jun 15, 2022, 10:33 AM)_

**Comment by byewokko** [comment]
The endpoint is actually `/tenant_propose` without the `/public`. This was fixed in new versions of the UI (Jun 17 2022).
